# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  default

steps:

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(System.DefaultWorkingDirectory)/EmptyFunctionApp/EmptyFunctionApp/EmptyFunctionApp.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: '$(Build.BinariesDirectory)'
#     includeRootFolder: true
#     archiveType: 'zip'
#     archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
#     replaceExistingArchive: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '$(Build.BuildId).zip'
    TargetFolder: '$(System.DefaultWorkingDirectory)/'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Azure subscription 1 (045686a6-27b2-4941-a615-4d117d53b326)'
    appType: 'functionApp'
    appName: 'PentaProxyTest'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'